---
title: "Lab4_Demo"
author: "Javier Patrón"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)     # for data wrangling
library(ggplot2)   # for awesome plotting
library(rsample)   # for data splitting
library(caret)     # for logistic regression modeling
library(recipes)
library(tidymodels)
```

Let's explore how employee income and overtime hours affect likelihood of employee attrition.  Any predictions?

```{r}
# Load the data
data("attrition", package = "modeldata")
df <- attrition %>% mutate_if(is.ordered, factor, ordered = FALSE)


# Create training (70%) and test (30%) sets for the 
# rsample::attrition data.
set.seed(123)  # for reproducibility (random sample)
churn_split <- initial_split(df, prop = .70)
churn_train <- training(churn_split)
churn_test  <- testing(churn_split)
```

Make the column of Attrition a numeric variable

```{r recode_attrition_test}

churn_test <- recipe(Attrition ~ ., data = churn_test) |> 
  step_integer(Attrition, zero_based = T) |> 
  prep(df) |> 
  bake(df)


```

```{r recode_attrition_train}

churn_train <- recipe(attrition ~ ., data = churn_train) %>%
  step_integer(attrition, zero_based = TRUE) %>%
  prep(churn_train) %>%
  bake(churn_train)


```


```{r specify_models_glm}
#Monthly Income
model1 <- glm(data = churn_train, 
              Attrition ~ MonthlyIncome,
              family = "binomial")

  
#OverTime
model2 <- glm(data = churn_train, 
              Attrition ~ OverTime,
              family = binomial)

```


```{r tidy_model_objs}

tidy(model1)
tidy(model2)

```

```{r exp_coefs}
#exponentiate the coefficients from model objects for interpretation

exp(coef(model1))
exp(coef(model2))


# To predict your exp(coef()) results you 

```

```{r plot_income_attrition}

ggplot(churn_test, aes(x = MonthlyIncome, y = Attrition)) + 
  geom_point() +
  stat_smooth(method = "glm",  
                  se = TRUE,
                  method.args = list(family = "binomial"))
                
```



We can add additional predictors, creating a multiple logistic regression model
``` {r mult_log_regression}
model3 <- glm(
  attrition ~ monthly_income + over_time,
  family = "binomial", 
  data = churn_train)

tidy(model3)

```



